version: '3.3'

services:
  db:
    image: postgres
    ports:
      - "5430:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "gdfstudio"
      POSTGRES_DB: "els"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql